### ISSUE TITLE
spanner: github.com/golang/protobuf v1.4.0 causing TestSample to panic

### ISSUE THREAD

**Issue by tbpg** [GoogleCloudPlatform/golang-samples#1346]
```
$ cd spanner/spanner_snippets
$ go test -v -run TestSample
=== RUN   TestSample
--- PASS: TestSample (125.75s)
PASS
ok  	github.com/GoogleCloudPlatform/golang-samples/spanner/spanner_snippets	125.853s$ go get github.com/golang/protobuf@v1.4.0
$ go test -v -run TestSample              
=== RUN   TestSample
    TestSample: snippet_test.go:47: database projects/golang-samples-tests/instances/golang-samples-tests/databases/test-golang-samples-tests-3 exists in state READY. delete result: <nil>
--- FAIL: TestSample (148.57s)
panic: not implemented [recovered]
	panic: not implemented

goroutine 8 [running]:
testing.tRunner.func1.1(0xa58ae0, 0xc66630)
	/usr/local/go/src/testing/testing.go:941 +0x3d0
testing.tRunner.func1(0xc0000bc5a0)
	/usr/local/go/src/testing/testing.go:944 +0x3f9
panic(0xa58ae0, 0xc66630)
	/usr/local/go/src/runtime/panic.go:967 +0x15d
github.com/golang/protobuf/proto.(*InternalMessageInfo).Merge(...)
	/home/tbp/go/pkg/mod/github.com/golang/protobuf@v1.4.0/proto/deprecated.go:90
google.golang.org/genproto/googleapis/spanner/v1.(*ExecuteSqlRequest_QueryOptions).XXX_Merge(...)
	/home/tbp/go/pkg/mod/google.golang.org/genproto@v0.0.0-20200413115906-b5235f65be36/googleapis/spanner/v1/spanner.pb.go:720
cloud.google.com/go/spanner.QueryOptions.merge(...)
	/home/tbp/go/pkg/mod/cloud.google.com/go/spanner@v1.4.0/transaction.go:235
cloud.google.com/go/spanner.(*txReadOnly).QueryWithOptions(0xc0007b8308, 0xc8b900, 0xc00003c0c0, 0xba43a6, 0x35, 0x0, 0x0, 0xc000290510, 0xc000242a80)
	/home/tbp/go/pkg/mod/cloud.google.com/go/spanner@v1.4.0/transaction.go:258 +0x52
github.com/GoogleCloudPlatform/golang-samples/spanner/spanner_snippets.queryWithQueryOptions(0xc8b900, 0xc00003c0c0, 0xc7a4c0, 0xc0002904e0, 0xc0001e2750, 0x0, 0x0)
	/home/tbp/go/src/github.com/GoogleCloudPlatform/golang-samples/spanner/spanner_snippets/snippet.go:1636 +0xdc
github.com/GoogleCloudPlatform/golang-samples/spanner/spanner_snippets.run(0xc8b900, 0xc00003c0c0, 0xc0001df800, 0xc0001e2750, 0xc7a4c0, 0xc0002904e0, 0xb8f222, 0x15, 0xc000040230, 0x62, ...)
	/home/tbp/go/src/github.com/GoogleCloudPlatform/golang-samples/spanner/spanner_snippets/snippet.go:2315 +0x60e
github.com/GoogleCloudPlatform/golang-samples/spanner/spanner_snippets.initTest.func1(0xc0000bc5a0, 0xb8f222, 0x15, 0xc000040230, 0x62, 0xc0007d6500, 0x91)
	/home/tbp/go/src/github.com/GoogleCloudPlatform/golang-samples/spanner/spanner_snippets/snippet_test.go:54 +0x100
github.com/GoogleCloudPlatform/golang-samples/spanner/spanner_snippets.TestSample(0xc0000bc5a0)
	/home/tbp/go/src/github.com/GoogleCloudPlatform/golang-samples/spanner/spanner_snippets/snippet_test.go:297 +0x212a
testing.tRunner(0xc0000bc5a0, 0xbb5ab8)
	/usr/local/go/src/testing/testing.go:992 +0xdc
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1043 +0x357
exit status 2
FAIL	github.com/GoogleCloudPlatform/golang-samples/spanner/spanner_snippets	148.709s
```

Found in #1341.

github.com/golang/protobuf v1.4.0 was tagged 2 days ago, which is why this is coming up now.

Here is the relevant code. The panic is on line 1636.
https://github.com/GoogleCloudPlatform/golang-samples/blob/6df66f51daf6cfceb033295f712a50b35a6b25af/spanner/spanner_snippets/snippet.go#L1631-L1654

cc @dsnet @broady @noahdietz @codyoss @skuruppu 

Related to https://github.com/googleapis/google-cloud-go/issues/1815.

**Comment by dsnet** [comment]
The problem is that the code [directly calls `XXX_Merge`](https://github.com/googleapis/google-cloud-go/blob/cae4a01220f6e6d660ec45b8d89add85e5fd98b9/spanner/transaction.go#L235-L236). The protobuf compatibility document has stated that XXX_ fields are internal to the protobuf implementation and shouldn't be accessed by users.

The fix should be simple, call [`proto.Merge`](https://pkg.go.dev/github.com/golang/protobuf/proto?tab=doc#Merge) instead.

**Comment by tbpg** [comment]
Thanks. I sent https://code-review.googlesource.com/c/gocloud/+/54890 to fix it.

**Comment by tbpg** [comment]
Need a release of cloud.google.com/go/spanner, then we can upgrade this repo and close this issue.

**Comment by tbpg** [comment]
Filed https://github.com/googleapis/google-cloud-go/issues/1929 for the Spanner release.

**Comment by skuruppu** [comment]
Thanks for the fix @tbpg. @hengfengli did the [v1.5.1 release](https://github.com/googleapis/google-cloud-go/releases/tag/spanner%2Fv1.5.1) which includes your fix. I think you should be able to close this now.

**Comment by tbpg** [comment]
Tested locally and it works. Thanks!
