### ISSUE TITLE
storagetransfer: unskip tests

### ISSUE THREAD

**Issue by tritone** [GoogleCloudPlatform/golang-samples#3205]
Tests for the storagetransfer submodule are currently all skipped due to a kokoro infrastructure issue. Sample error:

```
++ gcloud secrets versions access latest --project cloud-devrel-kokoro-resources --secret=go-storagetransfer-aws
github/golang-samples/testing/kokoro/system_tests.sh: line 104: gcloud: command not found
+ export STS_AWS_SECRET=
+ STS_AWS_SECRET=
++ S=
++ python3 -c 'import json,sys,os;obj=json.loads(os.getenv("S"));print (obj["AccessKeyId"]);'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
+ export AWS_ACCESS_KEY_ID=
+ AWS_ACCESS_KEY_ID=
```

It looks like the gcloud command is being run before gcloud is installed on the image. This can be fixed either by changing when this is executed, or calling gcloud from within TestMain instead.

**Comment by danielbankhead** [comment]
@JesseLovelace's OOO, will ping once he's back.

**Comment by JesseLovelace** [comment]
This issue was fixed in https://github.com/GoogleCloudPlatform/golang-samples/pull/3200/files, and all the tests were unskipped
