### ISSUE TITLE
healthcare: flaky test timeout

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/golang-samples#969]
seen during numerous nightly e2e tests

sponge/819a619d-eeef-45cc-b16e-91cf30b783a0

```
=== RUN   TestDataset
panic: test timed out after 45m0s

goroutine 2595 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1296 +0xfd
created by time.goFunc
	/usr/local/go/src/time/sleep.go:172 +0x44

goroutine 1 [chan receive, 44 minutes]:
testing.(*T).Run(0xc000276200, 0xaa7c61, 0xb, 0xacabf0, 0x480a96)
	/usr/local/go/src/testing/testing.go:879 +0x383
testing.runTests.func1(0xc000276100)
	/usr/local/go/src/testing/testing.go:1119 +0x78
testing.tRunner(0xc000276100, 0xc00023de08)
	/usr/local/go/src/testing/testing.go:827 +0xbf
testing.runTests(0xc00000cb60, 0xf647e0, 0x4, 0x4, 0x40d81f)
	/usr/local/go/src/testing/testing.go:1117 +0x2aa
testing.(*M).Run(0xc000118400, 0x0)
	/usr/local/go/src/testing/testing.go:1034 +0x165
main.main()
	_testmain.go:48 +0x13d

goroutine 6 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0000b6820)
	/tmpfs/src/gopath/pkg/mod/go.opencensus.io@v0.22.0/stats/view/worker.go:154 +0x100
created by go.opencensus.io/stats/view.init.0
	/tmpfs/src/gopath/pkg/mod/go.opencensus.io@v0.22.0/stats/view/worker.go:32 +0x57

goroutine 7 [sleep]:
time.Sleep(0x3b9aca00)
	/usr/local/go/src/runtime/time.go:105 +0x14f
github.com/GoogleCloudPlatform/golang-samples/healthcare.deidentifyDataset(0xb3c760, 0xf8ddd0, 0xc00002410a, 0x16, 0xaa8189, 0xb, 0xaa769f, 0xa, 0xaaf550, 0x17, ...)
	/tmpfs/src/gopath/src/github.com/GoogleCloudPlatform/golang-samples/healthcare/dataset_deidentify.go:67 +0x700
github.com/GoogleCloudPlatform/golang-samples/healthcare.TestDataset.func5(0xc0004f4a80)
	/tmpfs/src/gopath/src/github.com/GoogleCloudPlatform/golang-samples/healthcare/dataset_test.go:80 +0x85
github.com/GoogleCloudPlatform/golang-samples/internal/testutil.Retry(0xc000276200, 0xa, 0x77359400, 0xc0001d9ee0, 0x1)
	/tmpfs/src/gopath/src/github.com/GoogleCloudPlatform/golang-samples/internal/testutil/retry.go:34 +0xc3
github.com/GoogleCloudPlatform/golang-samples/healthcare.TestDataset(0xc000276200)
	/tmpfs/src/gopath/src/github.com/GoogleCloudPlatform/golang-samples/healthcare/dataset_test.go:79 +0x638
testing.tRunner(0xc000276200, 0xacabf0)
	/usr/local/go/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:878 +0x35c

goroutine 70 [IO wait]:
internal/poll.runtime_pollWait(0x7f467e95ef00, 0x72, 0xc000053870)
	/usr/local/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc0001c0398, 0x72, 0xffffffffffffff00, 0xb3cc00, 0xf25710)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc0001c0398, 0xc000457400, 0x400, 0x400)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc0001c0380, 0xc000457400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc0001c0380, 0xc000457400, 0x400, 0x400, 0x40a7ab, 0xc000010000, 0x9e5700)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000314020, 0xc000457400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:177 +0x68
crypto/tls.(*block).readFromUntil(0xc00026c300, 0xb3bb20, 0xc000314020, 0x5, 0xc000314020, 0x488ce2)
	/usr/local/go/src/crypto/tls/conn.go:492 +0x89
crypto/tls.(*Conn).readRecord(0xc000106000, 0xacc017, 0xc000106120, 0x10)
	/usr/local/go/src/crypto/tls/conn.go:593 +0xdd
crypto/tls.(*Conn).Read(0xc000106000, 0xc000452000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1145 +0xf1
bufio.(*Reader).Read(0xc00006c7e0, 0xc000560498, 0x9, 0x9, 0xc000053c50, 0xc000053ca8, 0x65315d)
	/usr/local/go/src/bufio/bufio.go:216 +0x22f
io.ReadAtLeast(0xb3ad20, 0xc00006c7e0, 0xc000560498, 0x9, 0x9, 0x9, 0xc000053cf0, 0x6b2678, 0xc000106000)
	/usr/local/go/src/io/io.go:310 +0x88
io.ReadFull(0xb3ad20, 0xc00006c7e0, 0xc000560498, 0x9, 0x9, 0x6ecea4, 0x7f467e9689f0, 0xc000106000)
	/usr/local/go/src/io/io.go:329 +0x58
net/http.http2readFrameHeader(0xc000560498, 0x9, 0x9, 0xb3ad20, 0xc00006c7e0, 0x0, 0xc000000000, 0x42d271, 0xacc0e8)
	/usr/local/go/src/net/http/h2_bundle.go:1545 +0x7b
net/http.(*http2Framer).ReadFrame(0xc000560460, 0xc0003069e0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/h2_bundle.go:1803 +0xa3
net/http.(*http2clientConnReadLoop).run(0xc000053fb8, 0xacba50, 0xc000040fb8)
	/usr/local/go/src/net/http/h2_bundle.go:8263 +0x9e
net/http.(*http2ClientConn).readLoop(0xc0004bea80)
	/usr/local/go/src/net/http/h2_bundle.go:8191 +0x76
created by net/http.(*http2Transport).newClientConn
	/usr/local/go/src/net/http/h2_bundle.go:7264 +0x636
FAIL	github.com/GoogleCloudPlatform/golang-samples/healthcare	2700.011s
```

**Comment by tbpg** [comment]
I haven't seen this in over a week. Closing for now.
